travis:
  secure:
    BINSTAR_TOKEN: ZKtypOZH60tIlwm8MrdnFIwl3Ukp4fviyXb4g6gje3mO8M2nMIeUXVuS6EQ4nsRwlyBq63/zSWpK5QHW+QKMo2iRSdUCQBwUgbH1k3RU6xKhieC+as/rlkVh/ALvQ0TPzPQlII/C1ji0Ozu4NoLSBx8g+P+5iBiiy5pOVhIPiEa7GAEs0AjHQl/9H1Nl16W+ZvSWQcBDKdMWWspgZr6rrWRETKsOiv13Znj4H5kZjEOtm+A5hTnL29AHMea7gdOuXViahJFKAY3A7+5+JzfacwLUAPislZ2/7LMuKC9Z+Vj7R52KQdOf7w+9pC0KOevuqtExE38lHnmiQ7OFa56fI9c8pjwSPFV5xwz9k1jWiAAdw7NOzYVJ6YIKRFehRp86VMR3IwqOcYodSaIcmko88gpKDRFvKeCyi7tQGvQmpZ9nZgx9mfw0WC44Rx8xJOVo+dV+NJOiEDRm4hM9RqObB1GXjYECfPD4ud4epjlhoPfPmjliWLinze5yMk4GPgd78ntfnlrENrAmrp/DNll+qYSz4VgpXC47P//rw2yisB3BW+GYswWN4eDfu1uzLaL8bCBQ3TqFvuM2MAnl1RSoYspJshCyEwZ49x8UtxHIejxRdVpLlhJ5xkz695wPxhVZALWg/RtyFpSSUU0BgebOHIsppPnRqn9WTqSwmbjR7Lo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
